# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: expense-service
# #   namespace: sdx-assignment-bibimarw
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: expense-service
# #   template:
# #     metadata:
# #       labels:
# #         app: expense-service
# #     spec:
# #       containers:
# #         - name: expense-service
# #           image: marwakhan/expense_service:1.0
# #           ports:
# #             - containerPort: 8002
# #           env:
# #             - name: DATABASE_HOST
# #               value: "expense_service"  # Replace with your actual database service name
# #             - name: DATABASE_PORT
# #               value: "5432"
# #             - name: DATABASE_USER
# #               value: "postgres"
# #             - name: DATABASE_PASSWORD
# #               value: "root"
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: expense-service
# #   namespace: sdx-assignment-bibimarw
# # spec:
# #   ports:
# #     - port: 80
# #       targetPort: 8002
# #   selector:
# #     app: expense-service
# # ---
# # apiVersion: route.openshift.io/v1
# # kind: Route
# # metadata:
# #   name: expense-service-route
# #   namespace: sdx-assignment-bibimarw
# # spec:
# #   host: expense-service.bibimarw.2.rahtiapp.fi
# #   to:
# #     kind: Service
# #     name: expense-service
# #   port:
# #     targetPort: 80

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: expense-service
#   namespace: sdx-assignment-bibimarw
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: expense-service
#   template:
#     metadata:
#       labels:
#         app: expense-service
#     spec:
#       containers:
#         - name: expense-service
#           image: marwakhan/expense_service:1.0
#           ports:
#             - containerPort: 8002
#           env:
#             - name: DATABASE_HOST
#               value: "expense_service"  # Replace with your actual database service name
#             - name: DATABASE_PORT
#               value: "5432"
#             - name: DATABASE_USER
#               value: "postgres"
#             - name: DATABASE_PASSWORD
#               value: "root"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expense-service
#   namespace: sdx-assignment-bibimarw
# spec:
#   ports:
#     - port: 80
#       targetPort: 8002
#   selector:
#     app: expense-service

# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: expense-service-route
#   namespace: sdx-assignment-bibimarw
# spec:
#   host: expense-service.bibimarw.2.rahtiapp.fi
#   to:
#     kind: Service
#     name: expense-service
#   port:
#     targetPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
  namespace: sdx-assignment-bibimarw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: marwakhan/expense_service:1.0
          ports:
            - containerPort: 8002
              # protocol: TCP
          env:
            - name: DATABASE_HOST
              value: "expense_db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "root"
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"


---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: sdx-assignment-bibimarw
spec:
  ports:
    - port: 80
      targetPort: 8002
  selector:
    app: expense-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: expense-service-route
  namespace: sdx-assignment-bibimarw
spec:
  host: expense-service.bibimarw.2.rahtiapp.fi
  to:
    kind: Service
    name: expense-service
  port:
    targetPort: 80
  tls:
    termination: edge   
    insecureEdgeTerminationPolicy: Redirect  # Redirect HTTP to HTTPS
