apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: sdx-assignment-bibimarw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: marwakhan/auth_service:1.0  #my image
          ports:
            - containerPort: 8001  
          env:
            - name: DATABASE_HOST
              value: "auth_db"  # database service name
            - name: DATABASE_PORT
              value: "5432"  
            - name: DATABASE_USER
              value: "postgres"  
            - name: DATABASE_PASSWORD
              value: "root"  
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: sdx-assignment-bibimarw
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8001  # container's port
  selector:
    app: auth-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: auth-service-route
  namespace: sdx-assignment-bibimarw
spec:
  host: auth-service.bibimarw.2.rahtiapp.fi 
  to:
    kind: Service
    name: auth-service
  port:
    targetPort: 80 
